openapi:
  application:
    description: ${OPENAPI_DESCRIPTION:Autenticação OAuth2 e JWT}
    version: ${OPENAPI_VERSION:1.0.0}
    title: ${OPENAPI_TITLE:Autenticação}

security:
  config:
    allow-origin: ${ALLOW_ORIGIN:http://localhost:4200}
    with-client: ${CONFIG_WITH_CLIENT:angular}
    secret-client: ${CONFIG_SECRET_CLIENT}
    jwt-signing-key: ${JWT_SIGNING_KEY}
    secure-https: ${SECURE_HTTPS:false}
    context-path-token: ${CONTEXT_PATH_TOKEN:/oauth/token}
    token-validity-seconds: ${TOKEN_VALIDITY_SECONDS:43200}
    refresh-token-validity-seconds: ${REFRESH_TOKEN_VALIDITY_SECONDS:86400}

server:
  servlet:
    encoding:
      charset: UTF-8
    context-path: ${CONTEXT_PATH:/authentication/api/v1}
  port: ${SERVER_PORT:8083}

spring:
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
  application:
    name: authentication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authentication?useTimezone=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:210683}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/authentication?useTimezone=true&serverTimezone=UTC
    user: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:210683}

springdoc:
  swagger-ui:
    path: /authentication/api/v1/swagger-ui.html
  api-docs:
    path: authentication/v3/api-docs
