server:
  port: 8083
spring:
  application:
    name: authentication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authentication?useTimezone=true&serverTimezone=UTC
    username: root
    password: 210683
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/authentication?useTimezone=true&serverTimezone=UTC
    user: root
    password: 210683
springdoc:
  api-docs:
    path: authentication/v3/api-docs
